name       : dymo-cups-drivers
version    : 1.4.0
release    : 2
source     :
    - http://download.dymo.com/Software/Linux/dymo-cups-drivers-1.4.0.tar.gz : c60797e7e986ca329f46e9a6ab1cb6382383952b15685ed69fd91f3c7ed64f71
license    : GPL-2.0-or-later
component  : drivers.printer
summary    : CUPS drivers for Dymo labelwriters
description: |
    CUPS drivers for Dymo labelwriters
builddeps  :
    - cups-devel
setup      : |
    %patch -p1 < $pkgfiles/cups-ppd-header.patch
    %configure
build      : |
    %make
install    : |
    %make_install
